version: 2

sources:
  - name: staging
    database: zoomcamp-0
     # For postgres:
      #database: production
    schema: ny_taxi_data

      # loaded_at_field: record_loaded_at
    tables:
      - name: green_taxi
      - name: yellow_taxi
      - name: fhv
         # freshness:
           # error_after: {count: 6, period: hour}